name: camera_with_files
publish_to: "none" # Remove this line if you wish to publish to pub.dev
description: Make a Camera Module With Gallery View. It looks like whatsapp Camera Module.
version: 0.0.1+1
homepage: https://github.com/reiko-dev/camera_with_files

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Images viewer
  photo_gallery: ^1.1.1
  image_gallery_saver: ^1.7.1

  permission_handler: ^10.0.0

  camera: ^0.9.8+1
  video_player: ^2.4.5
  image: ^3.2.0

  # Storage related
  # Required to show the created files on the gallery of the O.S.
  media_scanner:
    git:
      url: https://github.com/reiko-dev/media_scanner.git
      ref: b19fa1a2d225bb1cd6de712663564e8487454706

  path_provider: ^2.0.11
  path: ^1.8.1

  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/placeholder.png
